export const testimonials = [
    {
        name: "Claudia",
        body: "Before I started training with Rodney I had tried several things to get in shape including class pass, boxing, barre, and working out at the gym on my own using videos. I felt pretty good about my results but it was always hard to get past a certain 'level' no matter how many days a week I worked out. I also didn't realize that I had terrible form, so I was constantly getting injured. This would often lead me to need to take time off from the gym and lose much of my results. Even after just the first month of working out with Rodney I saw significant differences in my looks, posture, strength level and endurance. He created a tailored program to help me achieve my goals, including plans for what I could do on the days I worked out on my own and guidelines to improve my nutrition. After a year of working out with him, my results had totally exceeded anything I could have imagined. I measured an inch taller from the dramatic improvement to my posture, I slimmed down several sizes and was strong as heck. I also felt such an incredible sense of accomplishment, which really boosted my mood and self-confidence. Rodney is truly an expert at holding clients accountable for being kind, patient, and hilarious. He is also an absolute professional that is constantly researching strategies that are evidenced to work while also keeping track of innovations in the field."
    },
    {
        name: "Delilh",
        body: "I've been working with Rodney for about six months now, and our training together has grown from self-paced workouts on TrueCoach to live Zoom workout sessions and, my personal favorite, weekly Kettlebell Club meets. It has been simply amazing to learn so much from Rodney - remotely, nonetheless - over such a short period of time. Through my remote sessions with Rodney, I have been able to nail down basic kettlebell movements such as the swing, snatch, and clean, as well as the Turkish getup (which seemed super difficult before I learned it!), and can now perform them confidently and with ease. He is able to break down complex movements into comprehensible bite size pieces, while explaining the body's structure and movements in a very straightforward manner. Through my sessions with Rodney, I have gained not only strength, but also, more importantly, a better understanding of my body, and all bodies in general. I highly recommend working with Rodney as a coach. I guarantee that you will learn a lot from him, whether it is through self-paced workouts or live workout sessions."
    },
    {
        name: "Michelle",
        body: "I had a great time working with Rodney. I was his client for a little over 3 years and I was always impressed by his knowledge and professionalism. He's also really organized and extremely reliable.I really enjoyed his positive attitude and creative approach when developing my program. I always felt at ease and trusted what he designed for me. He also provided me with a great understanding of functional training. As a result of working with Rodney, I gained the confidence, strength, and skills to workout consistently and independently using kettlebells and other equipment at the gym. I believe that Rodney loves what he does. I definitely recommend him as a coach and personal trainer."
    }
]